[package]
name = "wayland-clipboard-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = {version = "0.29.0", features = ["fs"]}
wayland-client = "0.31.8"
wayland-protocols-wlr = {version="0.3.6", features=["client"]}
