name: Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "**.markdown"
      - "**.rasi"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "**.markdown"
      - "**.rasi"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull apt
        run: sudo apt-get update
      - name: Install Wayland
        run: sudo apt install libwayland-dev

        # Build, test, and check formatting
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Check formatting
        run: cargo fmt --check

